version: '3.8'

services:
  car-service:
    image: ivanicov/car-management-service:2.0.3
    ports:
      - "9000:9000"
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: